version: 0.2

phases:
  pre_build:
    commands:
      - npm install
    build:
      commands:
        - npm run build
    post-build:
      commands:
        - aws s3 sync build/ s3://tome-treasures
