  version: 0.2

  phases:
    install:
      runtime-versions:
        nodejs: 20  # Specify Node.js version
    pre_build:
      commands:
        - npm install   # Install dependencies
    build:
      commands:
        - npm run build   # Build the React app
  artifacts:
    files:
      - '/build/*'

