version: 0.2

phases:
  pre_build:
    commands:
      - npm install
    build:
      commands:
        - npm run build
    post_build:
      commands:
        - aws s3 cp --recursive ./build s3://tome-treasures
        - aws cloudfront create-invalidation --distribution-id E2NU8XDLF18ZEA --path /\*
